name: Conservación de Islas
on: [push, pull_request]
jobs:
  actions:
    runs-on: ubuntu-18.04
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci .
    - name: Verifica el formato
      run: docker run islasgeci make format
    - name: Corre pruebas y calcula cobertura
      run: docker run islasgeci make coverage
    - name: Evalua resistencia a mutaciones
      run: docker run islasgeci make mutants